### ISSUE TITLE
where is the extra C going?

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#107]
@camerondow35 , I'm opening this issue to sort through what we can / should say about extra C in years with warm springs.

**Comment by camerondow35** [comment]
If this is referring to the reviewer who "wasn't satisfied" with our explanation of where extra C goes, I don't think we need to change much. I was glad they commented on that because it means we did a good job setting it up as a future research need. We don't know where it's going, so coming up with a satisfying story would be irresponsible, right? We want it to make people wonder.

**Comment by teixeirak** [comment]
I want to give this a bit more thought and improve the discussion.
