### ISSUE TITLE
reduce length and citation count

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#125]
@camerondow35 , FYI, we need to shorten this:

The typical length of an article with 3-4 modest display items (figures and tables) is 2000-2500 words (summary paragraph plus body text). We're currently at 3005 words and 1 modest + 2 large display items. Articles typically have 30-50 references (currently at 59)

**Comment by camerondow35** [comment]
cut @ibanez_forecasting_2010 because data were from Japan and south Korea, while Menzel_2006 is a comparable study that uses european data which is probably more comparable to NA

cut parmesan_globally_2003 because other leaf pheno sources are fine for what we need

Cut @friedl_tale_2014 because the paper is more about timing of warming being important for influencing pheno shifts. But we cited it here in a place where any of our leaf pheno sources could work.

Cut @menzel_growing_1999 this menzel is similar to the other but this one is older.

Cut @fu_variation_2014 because it is only cited once, and relates to winter warming, not to other reasons listed where it is cited.

Cut @tardif_influence_2006 because @kern_multiple_2013 and @roibu_climatic_2020 are adequate citations where tardiff is cut. We could even cut another one of the two remaining in my opinion.

**Comment by teixeirak** [comment]
Latest: We're currently at 2839 words and 1 modest + 2 large display items. Articles typically have 30-50 references (currently at 53)

**Comment by teixeirak** [comment]
We're still a bit above in terms of words and citations, but it's close enough that I think we should call it satisfactory and let the editor decide if it needs to be shortened.
