### ISSUE TITLE
new title

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/growth_phenology#139]
Current title is 143 characters, max is 75. (Ack!) 

Current:
"Warmer spring temperatures in temperate deciduous forests advance the timing of tree growth but have little effect on annual woody productivity"

Ideas: 
- "Warm springs affect temperate deciduous tree growth timing but not extent" (73 char)  -*does "extent" sound weird? (and "affect" is boring)* 
-  "Warm springs impact temperate deciduous tree growth timing but not extent" (73 char)
-  "Warm springs impact temperate deciduous tree growth timing but not magnitude" (76 char 👎  )
-   **"Warm springs alter temperate deciduous tree growth timing but not magnitude"** (75 char 🥇   )
- "Warm springs alter timing but not magnitude of temperate deciduous tree growth" (I like this better, but 78 char 👎 ) 
- **"Warm springs alter timing but not amount of temperate deciduous tree growth"** (75 char 🥇  )
-  **"Warm springs alter timing but not extent of temperate deciduous tree growth"** (75 char 🥇  - think I'm changing my mind on "extent" sounding weird...)

I think the three in bold are the best I can come up with for now. @camerondow35 , which do you prefer? Or do you have other suggestions?

I think my favorite is the 3rd option.

**Comment by camerondow35** [comment]
I think **"Warm springs alter timing but not amount of temperate deciduous tree growth"** is ok. 

> "Warm springs alter timing but not extent of temperate deciduous tree growth" (75 char 🥇 - think I'm changing my mind on "extent" sounding weird...)

"Extent" does sound a bit off to me. It seems like more of a spatial term to me.

I wonder if they're going to have a problem with us saying "amount/total of temperate deciduous tree growth" since we're only looking at stem growth? 

How about:
**"Warm springs alter timing of but not total stem growth in deciduous trees" - 73**

**Comment by camerondow35** [comment]
Or do we even need to include the "timing" part? 

**Warm Springs do not lead to increased stem growth in temperate deciduous trees** - 78... a little over
or
**Warm Springs do not lead to increased growth in temperate deciduous trees** - 73 if you want to get rid of the stem part

**Comment by teixeirak** [comment]
I think the best option we both accept is still  **Warm springs alter timing but not amount of temperate deciduous tree growth**. 

I feel that it's essential to include timing, as that's half the story. I also know some of the dendro coauthors would say that the lack of effect of spring temperatures is unsurprising (we've done the biggest analysis of this to date, but they have a strong sense of what to expect.)

I also think it's important to include "temperate". This makes a critical distinction from, say, tropical deciduous forests. 

Another option:

**Warm springs alter timing but not *volume* of temperate deciduous tree growth**.  This would also help to address the comment of reviewer 2, although it's not necessary to put volume in the title to give an adequate response.

**Comment by teixeirak** [comment]
@camerondow35 , @rudeboybert , @ValentineHerr, we need to settle on a title. Cam & I have discussed options and at the moment it comes down to two options:

1. Warm springs alter timing but not *amount* of temperate deciduous tree growth. (75 char)
2. Warm springs alter timing but not *volume* of temperate deciduous tree growth. (75 char)
3. other?

It would be good to hear opinions.

**Comment by teixeirak** [comment]
I'd prefer magnitude, but that puts us over the 75 char limit.

**Comment by teixeirak** [comment]
updated:

1.  Warm springs alter timing but not amount of temperate deciduous tree growth. (75 char)
2.   Warm springs alter timing but not volume of temperate deciduous tree growth. (75 char)
3. Warm springs alter timing but not extent of temperate deciduous tree growth (75 char)

from offline chat, @rudeboybert  and I both think 3 is a better option than 1 or 2. @camerondow35 , you weren't so sure about "extent", but what do you think in this context?

**Comment by ValentineHerr** [comment]
I am not a fan of "extent" but probably because I encounter that word more in the GIS world.

I just looked a some synonyms  and found "breadth". Would that work?
Or, would putting growth before help? like "... total growth of temperate deciduous trees"? or "... overall growth of temperate deciduous trees"?
 
These are just some other suggestions, I'd be fine with any of 1.2.3 above.

**Comment by camerondow35** [comment]
I agree with Valentine about "extent", to me it's used more to describe the spatial extent of something. 

> Or, would putting growth before help?

I actually like this idea! So: "Warm springs alter timing but not total growth of temperate deciduous trees" but removing the "of" could be weird.

Since I have the least experience with picking titles, i'm fine with whatever you all think is best.

**Comment by teixeirak** [comment]
I think we have the solution!  

"**Warm springs alter timing but not total growth of temperate deciduous trees**" is perfect.

**Comment by rudeboybert** [comment]
CLEAN

**Comment by teixeirak** [comment]
I loved all your reactions, @rudeboybert !
